//! exo:host/crypto — SHA-256 and HMAC-SHA256 operations.
//!
//! Implements the `crypto::Host` trait generated by `bindgen!`.

use hmac::{Hmac, Mac};
use sha2::{Digest, Sha256};

use crate::connector::exo::connector::crypto;
use crate::state::WasmState;

type HmacSha256 = Hmac<Sha256>;

impl crypto::Host for WasmState {
    fn sha256(&mut self, data: Vec<u8>) -> wasmtime::Result<String> {
        self.policy.check_crypto().map_err(|e| wasmtime::Error::msg(e.to_string()))?;

        let hash = Sha256::digest(&data);
        Ok(hex_encode(&hash))
    }

    fn hmac_sha256(&mut self, key: Vec<u8>, data: Vec<u8>) -> wasmtime::Result<Vec<u8>> {
        self.policy.check_crypto().map_err(|e| wasmtime::Error::msg(e.to_string()))?;

        let mut mac =
            HmacSha256::new_from_slice(&key).map_err(|e| wasmtime::Error::msg(e.to_string()))?;
        mac.update(&data);
        Ok(mac.finalize().into_bytes().to_vec())
    }
}

/// Encode bytes as hex string.
fn hex_encode(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}
