//! exo:connector/http — policy-gated outbound HTTP requests.
//!
//! Implements the `http::Host` trait generated by `bindgen!`.
//! Every request checks `policy.check_http(url)` before sending.
//! Uses `WasmResourcePool.http_client` (reqwest::blocking::Client).

use crate::connector::exo::connector::http;
use crate::state::WasmState;

/// Maximum response body size (1MB).
const MAX_RESPONSE_BODY: usize = 1_048_576;

impl http::Host for WasmState {
    fn request(
        &mut self,
        method: String,
        url: String,
        headers: Vec<(String, String)>,
        body: Option<String>,
    ) -> wasmtime::Result<Result<http::HttpResponse, String>> {
        // 1. Policy check
        self.policy.check_http(&url).map_err(|e| wasmtime::Error::msg(e.to_string()))?;

        // 2. Build request
        let client = &self.resource_pool.http_client;
        let req_method = method
            .parse::<reqwest::Method>()
            .map_err(|e| wasmtime::Error::msg(format!("invalid HTTP method: {e}")))?;

        let mut builder = client.request(req_method, &url);
        for (key, value) in &headers {
            builder = builder.header(key.as_str(), value.as_str());
        }
        if let Some(ref body_str) = body {
            builder = builder.body(body_str.clone());
        }

        // 3. Send request
        let response = match builder.send() {
            Ok(resp) => resp,
            Err(e) => return Ok(Err(format!("HTTP request failed: {e}"))),
        };

        // 4. Parse response
        let status = response.status().as_u16();
        let resp_headers: Vec<(String, String)> = response
            .headers()
            .iter()
            .map(|(k, v)| (k.to_string(), v.to_str().unwrap_or("").to_string()))
            .collect();

        let resp_body = match response.text() {
            Ok(text) => {
                if text.len() > MAX_RESPONSE_BODY {
                    text[..MAX_RESPONSE_BODY].to_string()
                } else {
                    text
                }
            }
            Err(e) => return Ok(Err(format!("failed to read response body: {e}"))),
        };

        Ok(Ok(http::HttpResponse { status, headers: resp_headers, body: resp_body }))
    }
}

#[cfg(test)]
mod tests {
    use std::sync::Arc;

    use wasmtime::component::ResourceTable;
    use wasmtime_wasi::WasiCtxBuilder;

    use super::*;
    use crate::policy::CapabilityPolicy;
    use crate::resource_pool::WasmResourcePool;

    fn extract_mock_hostname(url: &str) -> String {
        let without_scheme =
            url.strip_prefix("http://").or_else(|| url.strip_prefix("https://")).unwrap_or(url);
        let host_part = without_scheme.split('/').next().unwrap_or("");
        // Strip port — policy's extract_hostname does hostname.split(':').next()
        host_part.split(':').next().unwrap_or("").to_string()
    }

    fn test_state_with_http_policy(hosts: &[&str]) -> WasmState {
        let mut policy = CapabilityPolicy::deny_all();
        policy.http_patterns = hosts.iter().map(|h| crate::policy::HostPattern::parse(h)).collect();

        let pool = WasmResourcePool::new_for_test();

        WasmState {
            wasi_ctx: WasiCtxBuilder::new().build(),
            resource_table: ResourceTable::new(),
            policy: Arc::new(policy),
            resource_pool: Arc::new(pool),
            module_name: "test.http".to_string(),
        }
    }

    // ── E4S2-T7: HTTP request allowed succeeds ──

    #[test]
    fn http_request_allowed_succeeds() {
        let mut server = mockito::Server::new();
        let mock = server.mock("GET", "/test").with_status(200).with_body("hello").create();

        let mut state = test_state_with_http_policy(&[&extract_mock_hostname(&server.url())]);
        let result = http::Host::request(
            &mut state,
            "GET".into(),
            format!("{}/test", server.url()),
            vec![],
            None,
        )
        .unwrap();

        assert!(result.is_ok());
        let resp = result.unwrap();
        assert_eq!(resp.status, 200);
        assert_eq!(resp.body, "hello");
        mock.assert();
    }

    // ── E4S2-T8: HTTP request blocked by policy ──

    #[test]
    fn http_request_blocked_by_policy() {
        let mut state = test_state_with_http_policy(&["allowed.com"]);
        let result = http::Host::request(
            &mut state,
            "GET".into(),
            "https://evil.com/hack".into(),
            vec![],
            None,
        );

        // Policy violation should be a wasmtime::Error (trap)
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("denied"));
    }

    // ── E4S2-T9: HTTP request returns status, headers, body ──

    #[test]
    fn http_request_returns_status_headers_body() {
        let mut server = mockito::Server::new();
        let mock = server
            .mock("GET", "/headers")
            .with_status(201)
            .with_header("x-custom", "test-value")
            .with_body("response body")
            .create();

        let mut state = test_state_with_http_policy(&[&extract_mock_hostname(&server.url())]);
        let result = http::Host::request(
            &mut state,
            "GET".into(),
            format!("{}/headers", server.url()),
            vec![],
            None,
        )
        .unwrap()
        .unwrap();

        assert_eq!(result.status, 201);
        assert_eq!(result.body, "response body");
        assert!(result.headers.iter().any(|(k, v)| k == "x-custom" && v == "test-value"));
        mock.assert();
    }

    // ── E4S2-T10: HTTP POST with body ──

    #[test]
    fn http_request_post_with_body() {
        let mut server = mockito::Server::new();
        let mock = server
            .mock("POST", "/submit")
            .match_body(r#"{"key":"value"}"#)
            .with_status(200)
            .with_body("ok")
            .create();

        let mut state = test_state_with_http_policy(&[&extract_mock_hostname(&server.url())]);
        let result = http::Host::request(
            &mut state,
            "POST".into(),
            format!("{}/submit", server.url()),
            vec![("Content-Type".into(), "application/json".into())],
            Some(r#"{"key":"value"}"#.into()),
        )
        .unwrap()
        .unwrap();

        assert_eq!(result.status, 200);
        mock.assert();
    }

    // ── E4S2-T11: HTTP response body truncated at max ──

    #[test]
    fn http_request_body_truncated_at_max() {
        let mut server = mockito::Server::new();
        // Create a body larger than MAX_RESPONSE_BODY (1MB)
        let large_body = "x".repeat(MAX_RESPONSE_BODY + 1000);
        let mock = server.mock("GET", "/large").with_status(200).with_body(&large_body).create();

        let mut state = test_state_with_http_policy(&[&extract_mock_hostname(&server.url())]);
        let result = http::Host::request(
            &mut state,
            "GET".into(),
            format!("{}/large", server.url()),
            vec![],
            None,
        )
        .unwrap()
        .unwrap();

        assert_eq!(result.body.len(), MAX_RESPONSE_BODY);
        mock.assert();
    }
}
