//! exo:host/kv — per-module key-value store (SQLite-backed).
//!
//! Implements the `kv::Host` trait generated by `bindgen!`.

use crate::connector::exo::connector::kv;
use crate::state::WasmState;

impl kv::Host for WasmState {
    fn get(&mut self, key: String) -> wasmtime::Result<Option<String>> {
        self.policy.check_kv().map_err(|e| wasmtime::Error::msg(e.to_string()))?;

        Ok(self.resource_pool.kv_get(&self.module_name, &key))
    }

    fn set(&mut self, key: String, value: String) -> wasmtime::Result<()> {
        self.policy.check_kv().map_err(|e| wasmtime::Error::msg(e.to_string()))?;

        self.resource_pool.kv_set(&self.module_name, &key, &value);
        Ok(())
    }

    fn delete(&mut self, key: String) -> wasmtime::Result<bool> {
        self.policy.check_kv().map_err(|e| wasmtime::Error::msg(e.to_string()))?;

        Ok(self.resource_pool.kv_delete(&self.module_name, &key))
    }

    fn list_keys(&mut self, prefix: String) -> wasmtime::Result<Vec<String>> {
        self.policy.check_kv().map_err(|e| wasmtime::Error::msg(e.to_string()))?;

        Ok(self.resource_pool.kv_list_keys(&self.module_name, &prefix))
    }
}
