//! exo:host/logging — structured logging to the host's tracing infrastructure.
//!
//! Implements the `logging::Host` trait generated by `bindgen!`.

use crate::connector::exo::connector::logging;
use crate::state::WasmState;

impl logging::Host for WasmState {
    fn log(&mut self, level: logging::LogLevel, message: String) -> wasmtime::Result<()> {
        self.policy.check_logging().map_err(|e| wasmtime::Error::msg(e.to_string()))?;

        let module = &self.module_name;
        match level {
            logging::LogLevel::Trace => tracing::trace!(module = %module, "{}", message),
            logging::LogLevel::Debug => tracing::debug!(module = %module, "{}", message),
            logging::LogLevel::Info => tracing::info!(module = %module, "{}", message),
            logging::LogLevel::Warn => tracing::warn!(module = %module, "{}", message),
            logging::LogLevel::Error => tracing::error!(module = %module, "{}", message),
        }
        Ok(())
    }
}
