//! Host function implementations for WASM connector modules.
//!
//! These implement the traits generated by `bindgen!` in `connector.rs`.
//! Every host function checks the module's `CapabilityPolicy` before
//! performing any I/O.

// Custom Exo interfaces (policy check per call)
pub mod crypto;
pub mod http;
pub mod kv;
pub mod logging;
pub mod process;
pub mod sockets;
pub mod websocket;

// WASI standard/scoped (handled by wasmtime-wasi, policy at configuration time)
pub mod clocks;
pub mod environment;
pub mod filesystem;
pub mod random;

use wasmtime::component::{HasSelf, Linker};

use crate::state::WasmState;

/// Register all custom Exo host functions on the Linker.
///
/// This is called by `WasmRuntime::new()`. The `bindgen!`-generated
/// `ConnectorWorld::add_to_linker` handles this, so we just delegate.
pub fn register_all(linker: &mut Linker<WasmState>) -> Result<(), anyhow::Error> {
    // The bindgen! macro in connector.rs generates add_to_linker which
    // registers all the custom interface implementations.
    // We call it here using the generated function.
    crate::connector::ConnectorWorld::add_to_linker::<_, HasSelf<_>>(linker, |state| state)?;
    Ok(())
}
