//! exo:host/process — scoped process execution (policy-gated).
//!
//! Implements the `process::Host` trait generated by `bindgen!`.

use std::time::Duration;

use crate::connector::exo::connector::process;
use crate::state::WasmState;

const DEFAULT_TIMEOUT_MS: u32 = 30_000;
const MAX_TIMEOUT_MS: u32 = 60_000;
const MAX_OUTPUT_BYTES: usize = 262_144; // 256KB

impl process::Host for WasmState {
    fn exec(
        &mut self,
        command: String,
        args: Vec<String>,
        timeout_ms: Option<u32>,
    ) -> wasmtime::Result<Result<process::ExecResult, String>> {
        self.policy.check_process(&command).map_err(|e| wasmtime::Error::msg(e.to_string()))?;

        let timeout = Duration::from_millis(
            timeout_ms.unwrap_or(DEFAULT_TIMEOUT_MS).min(MAX_TIMEOUT_MS) as u64,
        );

        // Spawn the process
        let child = std::process::Command::new(&command)
            .args(&args)
            .stdout(std::process::Stdio::piped())
            .stderr(std::process::Stdio::piped())
            .env_clear()
            .spawn();

        let mut child = match child {
            Ok(c) => c,
            Err(e) => return Ok(Err(format!("failed to spawn '{command}': {e}"))),
        };

        // Wait with timeout
        let start = std::time::Instant::now();
        loop {
            match child.try_wait() {
                Ok(Some(status)) => {
                    let stdout = read_bounded(child.stdout.take(), MAX_OUTPUT_BYTES);
                    let stderr = read_bounded(child.stderr.take(), MAX_OUTPUT_BYTES);
                    return Ok(Ok(process::ExecResult {
                        stdout,
                        stderr,
                        exit_code: status.code(),
                        timed_out: false,
                    }));
                }
                Ok(None) => {
                    if start.elapsed() > timeout {
                        let _ = child.kill();
                        let _ = child.wait();
                        let stdout = read_bounded(child.stdout.take(), MAX_OUTPUT_BYTES);
                        let stderr = read_bounded(child.stderr.take(), MAX_OUTPUT_BYTES);
                        return Ok(Ok(process::ExecResult {
                            stdout,
                            stderr,
                            exit_code: None,
                            timed_out: true,
                        }));
                    }
                    std::thread::sleep(Duration::from_millis(10));
                }
                Err(e) => return Ok(Err(format!("wait error: {e}"))),
            }
        }
    }
}

fn read_bounded(pipe: Option<impl std::io::Read>, max_bytes: usize) -> String {
    let Some(mut pipe) = pipe else {
        return String::new();
    };
    let mut buf = vec![0u8; max_bytes];
    let n = pipe.read(&mut buf).unwrap_or_default();
    buf.truncate(n);
    String::from_utf8_lossy(&buf).into_owned()
}
