//! exo:connector/websocket — persistent WebSocket connections (policy-gated).
//!
//! Implements the `websocket::Host` trait generated by `bindgen!`.
//! Connections stored in `WasmResourcePool.websocket_connections`.
//! Async I/O bridged via `tokio::runtime::Handle::current().block_on()`.

use std::sync::Arc;
use std::time::Duration;

use futures_util::{SinkExt, StreamExt};
use tokio_tungstenite::tungstenite::Message;

use crate::connector::exo::connector::websocket;
use crate::resource_pool::WebSocketConnection;
use crate::state::WasmState;

impl websocket::Host for WasmState {
    fn connect(
        &mut self,
        id: String,
        url: String,
        headers: Vec<(String, String)>,
    ) -> wasmtime::Result<Result<(), String>> {
        // 1. Policy check — URL must match websocket_patterns
        self.policy.check_websocket(&url).map_err(|e| wasmtime::Error::msg(e.to_string()))?;

        // 2. Connect via tokio-tungstenite (async bridge)
        let result = tokio::runtime::Handle::current().block_on(async {
            use tokio_tungstenite::tungstenite::client::IntoClientRequest;

            // into_client_request() on a URL string generates the full WebSocket
            // upgrade request with sec-websocket-key and other required headers.
            let mut request =
                url.into_client_request().map_err(|e| format!("invalid request: {e}"))?;

            // Add custom headers on top of the auto-generated ones
            for (key, value) in &headers {
                match (
                    key.parse::<tokio_tungstenite::tungstenite::http::HeaderName>(),
                    value.parse::<tokio_tungstenite::tungstenite::http::HeaderValue>(),
                ) {
                    (Ok(name), Ok(val)) => {
                        request.headers_mut().insert(name, val);
                    }
                    _ => {
                        tracing::warn!(
                            header_key = %key,
                            "WebSocket connect: dropping invalid header"
                        );
                    }
                }
            }

            let (stream, _response) = tokio_tungstenite::connect_async(request)
                .await
                .map_err(|e| format!("WebSocket connect failed: {e}"))?;

            Ok::<_, String>(stream)
        });

        match result {
            Ok(stream) => {
                let conn =
                    Arc::new(WebSocketConnection { stream: tokio::sync::Mutex::new(stream) });
                self.resource_pool.ws_insert(id, conn);
                Ok(Ok(()))
            }
            Err(e) => Ok(Err(e)),
        }
    }

    fn send(&mut self, id: String, message: String) -> wasmtime::Result<Result<(), String>> {
        let conn = self.resource_pool.ws_get(&id).ok_or_else(|| {
            wasmtime::Error::msg(format!("WebSocket connection '{id}' not found"))
        })?;

        let result = tokio::runtime::Handle::current().block_on(async {
            let mut stream = conn.stream.lock().await;
            stream
                .send(Message::Text(message.into()))
                .await
                .map_err(|e| format!("WebSocket send failed: {e}"))
        });

        Ok(result)
    }

    fn recv(
        &mut self,
        id: String,
        timeout_ms: u32,
    ) -> wasmtime::Result<Result<Option<String>, String>> {
        let conn = self.resource_pool.ws_get(&id).ok_or_else(|| {
            wasmtime::Error::msg(format!("WebSocket connection '{id}' not found"))
        })?;

        let result = tokio::runtime::Handle::current().block_on(async {
            let mut stream = conn.stream.lock().await;

            if timeout_ms == 0 {
                // Non-blocking poll
                match tokio::time::timeout(Duration::from_millis(1), stream.next()).await {
                    Ok(Some(Ok(msg))) => Ok(extract_text(msg)),
                    Ok(Some(Err(e))) => Err(format!("WebSocket recv error: {e}")),
                    Ok(None) => Err("WebSocket connection closed".into()),
                    Err(_) => Ok(None), // timeout — no message
                }
            } else {
                let timeout = Duration::from_millis(timeout_ms as u64);
                match tokio::time::timeout(timeout, stream.next()).await {
                    Ok(Some(Ok(msg))) => Ok(extract_text(msg)),
                    Ok(Some(Err(e))) => Err(format!("WebSocket recv error: {e}")),
                    Ok(None) => Err("WebSocket connection closed".into()),
                    Err(_) => Ok(None), // timeout expired
                }
            }
        });

        Ok(result)
    }

    fn close(&mut self, id: String) -> wasmtime::Result<Result<(), String>> {
        let conn = self.resource_pool.ws_remove(&id).ok_or_else(|| {
            wasmtime::Error::msg(format!("WebSocket connection '{id}' not found"))
        })?;

        let result = tokio::runtime::Handle::current().block_on(async {
            let mut stream = conn.stream.lock().await;
            stream.close(None).await.map_err(|e| format!("WebSocket close failed: {e}"))
        });

        Ok(result)
    }
}

/// Extract text content from a WebSocket message.
/// Binary messages are hex-encoded. Ping/Pong/Close return None.
fn extract_text(msg: Message) -> Option<String> {
    match msg {
        Message::Text(t) => Some(t.to_string()),
        Message::Binary(b) => Some(hex::encode(&b)),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::policy::{CapabilityPolicy, HostPattern};
    use crate::resource_pool::WasmResourcePool;
    use wasmtime::component::ResourceTable;
    use wasmtime_wasi::WasiCtxBuilder;

    fn test_state_with_pool(patterns: &[&str], pool: Arc<WasmResourcePool>) -> WasmState {
        let mut policy = CapabilityPolicy::deny_all();
        policy.websocket_patterns = patterns.iter().map(|p| HostPattern::parse(p)).collect();

        WasmState {
            wasi_ctx: WasiCtxBuilder::new().build(),
            resource_table: ResourceTable::new(),
            policy: Arc::new(policy),
            resource_pool: pool,
            module_name: "test.ws".to_string(),
        }
    }

    /// Spawn a simple WebSocket echo server on a random port.
    async fn spawn_ws_echo_server() -> (String, tokio::task::JoinHandle<()>) {
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let addr = listener.local_addr().unwrap();
        let handle = tokio::spawn(async move {
            while let Ok((stream, _)) = listener.accept().await {
                tokio::spawn(async move {
                    let ws = tokio_tungstenite::accept_async(stream).await.unwrap();
                    let (mut write, mut read) = ws.split();
                    while let Some(Ok(msg)) = read.next().await {
                        if (msg.is_text() || msg.is_binary()) && write.send(msg).await.is_err() {
                            break;
                        }
                    }
                });
            }
        });
        (format!("ws://127.0.0.1:{}", addr.port()), handle)
    }

    /// Helper: run WebSocket tests with proper runtime management.
    ///
    /// - Resource pool created outside tokio (avoids reqwest nested runtime panic on drop)
    /// - Multi-thread runtime so spawn_blocking has access to Handle::current()
    /// - Host function calls run on blocking thread (they use Handle::current().block_on())
    fn run_ws_test<F>(patterns: &[&str], test_fn: F)
    where
        F: FnOnce(&mut WasmState, String) + Send + 'static,
    {
        let pool = Arc::new(WasmResourcePool::new_for_test());
        let patterns: Vec<String> = patterns.iter().map(|s| s.to_string()).collect();

        let rt = tokio::runtime::Builder::new_multi_thread().enable_all().build().unwrap();

        rt.block_on(async {
            let (url, _server) = spawn_ws_echo_server().await;
            let pattern_refs: Vec<&str> = patterns.iter().map(|s| s.as_str()).collect();
            let mut state = test_state_with_pool(&pattern_refs, pool.clone());

            // Run sync host function calls on a blocking thread
            // (they use Handle::current().block_on() internally)
            tokio::task::spawn_blocking(move || {
                test_fn(&mut state, url);
            })
            .await
            .unwrap();
        });
        // pool drops here, outside the async context — no panic
    }

    // ── E4S2-T12: WebSocket connect allowed ──

    #[test]
    fn websocket_connect_allowed() {
        run_ws_test(&["127.0.0.1"], |state, url| {
            let result = websocket::Host::connect(state, "test-conn".into(), url, vec![]).unwrap();
            assert!(result.is_ok(), "connect should succeed: {:?}", result);
            let _ = websocket::Host::close(state, "test-conn".into());
        });
    }

    // ── E4S2-T13: WebSocket connect blocked by policy ──

    #[test]
    fn websocket_connect_blocked() {
        // Policy check fails before connection — no server/runtime needed
        let pool = Arc::new(WasmResourcePool::new_for_test());
        let mut state = test_state_with_pool(&["allowed.com"], pool);

        let rt = tokio::runtime::Runtime::new().unwrap();
        let _guard = rt.enter();

        let result = websocket::Host::connect(
            &mut state,
            "test-conn".into(),
            "ws://evil.com/ws".into(),
            vec![],
        );

        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("denied"));
    }

    // ── E4S2-T14: WebSocket send/recv roundtrip ──

    #[test]
    fn websocket_send_recv_roundtrip() {
        run_ws_test(&["127.0.0.1"], |state, url| {
            websocket::Host::connect(state, "echo".into(), url, vec![]).unwrap().unwrap();
            websocket::Host::send(state, "echo".into(), "hello world".into()).unwrap().unwrap();
            let msg = websocket::Host::recv(state, "echo".into(), 1000).unwrap().unwrap();
            assert_eq!(msg, Some("hello world".into()));
            let _ = websocket::Host::close(state, "echo".into());
        });
    }

    // ── E4S2-T15: WebSocket recv timeout ──

    #[test]
    fn websocket_recv_timeout() {
        run_ws_test(&["127.0.0.1"], |state, url| {
            websocket::Host::connect(state, "timeout".into(), url, vec![]).unwrap().unwrap();
            let msg = websocket::Host::recv(state, "timeout".into(), 0).unwrap().unwrap();
            assert_eq!(msg, None);
            let msg = websocket::Host::recv(state, "timeout".into(), 50).unwrap().unwrap();
            assert_eq!(msg, None);
            let _ = websocket::Host::close(state, "timeout".into());
        });
    }

    // ── E4S2-T16: WebSocket close then send fails ──

    #[test]
    fn websocket_close_then_send_fails() {
        run_ws_test(&["127.0.0.1"], |state, url| {
            websocket::Host::connect(state, "closed".into(), url, vec![]).unwrap().unwrap();
            websocket::Host::close(state, "closed".into()).unwrap().unwrap();
            let result = websocket::Host::send(state, "closed".into(), "msg".into());
            assert!(result.is_err(), "send on closed connection should trap");
        });
    }

    // ── E4S2-T17: WebSocket connection persists in pool ──

    #[test]
    fn websocket_connection_persists_in_pool() {
        run_ws_test(&["127.0.0.1"], |state, url| {
            websocket::Host::connect(state, "persist".into(), url, vec![]).unwrap().unwrap();
            assert!(state.resource_pool.ws_get("persist").is_some());
            websocket::Host::close(state, "persist".into()).unwrap().unwrap();
            assert!(state.resource_pool.ws_get("persist").is_none());
        });
    }
}
